package com.bug.iwinner.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-23T14:12:13.291+08:00
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "EmployeeServiceImplService", 
                  wsdlLocation = "http://localhost:3737/wsServices/services/employeeservice?wsdl",
                  targetNamespace = "http://impl.ws.iwinner.bug.com/") 
public class EmployeeServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.iwinner.bug.com/", "EmployeeServiceImplService");
    public final static QName EmployeeServiceImplPort = new QName("http://impl.ws.iwinner.bug.com/", "EmployeeServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:3737/wsServices/services/employeeservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:3737/wsServices/services/employeeservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    /*public EmployeeServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmployeeServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmployeeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }
*/
    /**
     *
     * @return
     *     returns EmployeeServiceIF
     */
    @WebEndpoint(name = "EmployeeServiceImplPort")
    public EmployeeServiceIF getEmployeeServiceImplPort() {
        return super.getPort(EmployeeServiceImplPort, EmployeeServiceIF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServiceIF
     */
    @WebEndpoint(name = "EmployeeServiceImplPort")
    public EmployeeServiceIF getEmployeeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceImplPort, EmployeeServiceIF.class, features);
    }

}
