
package com.bug.iwinner.ws.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-23T14:12:13.103+08:00
 * Generated source version: 2.7.16
 */

@WebFault(name = "Exception", targetNamespace = "http://impl.ws.iwinner.bug.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.bug.iwinner.ws.impl.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.bug.iwinner.ws.impl.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.bug.iwinner.ws.impl.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.bug.iwinner.ws.impl.Exception getFaultInfo() {
        return this.exception;
    }
}
